# Практическая работа №3: Обработка выборочных данных. Нахождение интервальных оценок параметров распределения. Проверка статистической гипотезы о нормальном распределении

Выполнили студенты гр. 0382 Деткова Анна и Рубежова Наталия. Вариант №10

## Цель работы

Получение практических навыков вычисления интервальных статистических оценок параметров распределения выборочных данных и проверки «справедливости» статистических гипотез.

## Основные теоретические положения

&emsp;*__Статистические оценки:__*
> &emsp;*__Интервальная оценка__* - статистическая оценка, которая задается двумя числами - концами интервала, в котором может находиться значение параметра $θ$.

> &emsp;*__Точность__* $θ^*$ статистической оценки параметра $θ$ - значение $δ$, удовлетворяющее неравенству:
$$δ > |θ^* - θ| \ \ \ \ \ \ \ (1)$$
- Чем меньше значение $δ$, тем точнее оценка $θ$.

> &emsp;*__Надежность (доверительная вероятность)__* оценки $θ^*$ - вероятность $γ$, с которой выполняется неравенство (1):
$$γ = P\{δ > |θ^* - θ|\}$$
или
$$γ = P\{θ^* - δ < θ < θ^* + δ\}$$

> &emsp;Интервал $(θ^* - δ ; \ θ^* + δ)$ - *__доверительный интервал, интервальная оценка параметра $θ$__* <br>с вероятностью (надежностью) $γ$ содержит в себе (покрывает) истинное значение оцениваемого параметра $θ$.

&emsp; &emsp;image.png

&emsp;*__Виды интервальных оценок:__*

> &emsp;При *__двусторонней оценке__* задаются обе границы доверительного интервала, зависящие от доверительной вероятности $γ$:
$$P\{β_1(γ) < θ < β_2(γ)\} = p$$

> &emsp; Для *__одностороннего доверительного интеравала__* границы интервалов задаются так, чтобы:
$$P\{β(γ) > θ\} =γ$$
или
$$P\{β(γ) < θ\} =γ$$

&emsp;где $γ$ - *__уровень значимости.__*
> &emsp;Значение $α = 1 - γ$ называют *__уровнем значимости__*. <br>&emsp;Значение $γ$ задают обычно равным 0.95, 0.99, 0.995, 0.999.

&emsp;*__Статистические гипотезы:__*

> &emsp;*__Статистической гипотезой__* называют гипотезу о виде неизвестного распределения исследуемой случайной величины или о значении параметров известных распределений.

> &emsp;Выдвинутую гипотезу называют *__нулевой или основной гипотезой__* и обозначают $H_0$.

> &emsp;*__Конкурирующей или альтернативной__* называют гипотезу $H_1$, которая противоречит основной гипотезе.

> &emsp;Различают *__простые гипотезы__* (содержат только одно предположение) и *__сложные гипотезы__* (содержат более одного предположения).

&emsp;*__Проверка статистических гипотез:__*

> &emsp;*__Ошибка первого рода__* состоит в том, что нулевая гипотеза отвергается, хотя она верна.

> &emsp;*__Ошибка второго рода__* состоит в том, что нулевая гипотеза принимается, хотя она неверна.

> &emsp;Вероятность совершения ошибки первого рода называют *__уровнем значимости__* и обозначают $α$. Как правило, уровень значимости назначают равным от 0.001 до 0.2.

> &emsp;Величину $1 - β$ - вероятность того, что гипотеза отвергается, когда она верна, называют *__мощностью критерия__*.

> - &emsp;Принятие гипотезы не означает ее справедливость, а лишь констатирует, что, в соответствии с используемым критерием и уровнем значимости, гипотеза согласуется с данными наблюдений.
- &emsp;Для проверки статистических гипотез предлагаются различные критерии, которые представляют собой значения случайных величин, имеющих те или иные известные законы распределения.
- &emsp;При проверке статистических гипотез на основе выборочных данных вычисляются значения этих случайных величин (*__наблюденные значения__*), которые сопоставляются с некоторыми, так называемыми, *__критическими__* (зависящими от заданного уровня значимости $α$) *__значениями__* этих случайных величин. На основании этого сопоставления принимается решение о принятии или не принятии нулевой гипотезы.

&emsp;*__Области принятия/непринятия гипотез:__*

> &emsp;*__Областью принятия нулевой гипотезы__* называют совокупность значения критерия, при которых нулевую гипотезу принимают.

> &emsp;*__Критической областью__* называют совокупность значений критерия, при которых нулевую гипотезу отвергают.
Область принятия гипотезы и критическая область разделены точками, которые называются *__критическими значениями критерия__* $K_{кр}$
Область непринятия гипотезы может быть односторонней (правосторонней или левосторонней) и двусторонней

> &emsp;*__Правосторонней__* называют критическую область, определяемую неравенством $$K_{набл} > K_{кр}$$

> &emsp;*__Левосторонней__* называют критическую область, определяемую неравенством $$K_{набл} < K_{кр}$$

> &emsp;*__Двусторонней__* называют критическую область, определяемую неравенствами $$K_{набл} < K_{кр_1} \\ K_{набл} > K_{кр_2}$$

&emsp;*__Критерий Пирсона:__*
> &emsp;*__Критерий Пирсона (или критерий $χ^2$)__* - правосторонний критерий. Согласно этому критерию на основании выборочных данных вычисляется "наблюденное" значение случайной величины $χ^2$:
$$χ^2_{набл} = \sum^K_{i=1} \frac{(n_i - n_i')^2}{n_i'} $$
Здесь $n_i'$ - теоретические частоты - частоты, с которыми нормально распределенная величина с параметрами $\overline{x_в}$ и $S$ попала бы в $i$-й интервал интервального ряда при проведении $N$ испытаний.

 &emsp;Распределение  $χ^2$ зависит от числа свободы $k$, которое вычисляется по формуле (для нормального распределения):
$$k = K - 3$$

&emsp;По числу степеней свободы и уровню значимости вычисляется значение $χ^2_{крит} = χ^2(α,k)$. Это значение можно определить с помощью соответствующей таблицы.

&emsp;Критическая область (область непринятия гипотезы $H_0$) определяется неравенством:
$$χ^2_{набл} > χ^2_{крит}$$

## Постановка задачи

Для заданной надежности определить (на основании выборочных данных и результатов выполнения практической работы №2) границы доверительных интервалов для математического ожидания и среднеквадратичного отклонения случайной величины. Проверить гипотезу о нормальном распределении исследуемой случайной величины с помощью критерия Пирсона $\chi^2$. Дать содержательную интерпретацию полученным результатам.

## Выполнение работы


### *__Задание 1.__*
*Вычислить точность и доверительный интервал для математического ожидания при неизвестном среднеквадратичном отклонении при заданном объёме выборки для доверительной точности $γ∈\{0.95,0.99\}$. Сделать выводы.*

При неизвестном среднеквадратичном отклонении ($σ=σ(x)$ - неизвестно) для выборки с заданным объемом $N=117$:

Согласно условию, $σ=σ(x)$ - неизвестно. <br>
Тогда, введем в рассмотрение случайную величину $t$, которая распределена по закону $S(t, N)$ - закону Стьюдента с $k = N - 1$ степенями свободы:
$$t = \frac{\overline{x}_в - a}{S / \sqrt{N}}, \ где$$
- $N$ - объем выборки
- $\overline{x}_в$ - выборочное среднее
- $a$ - математическое ожидание
- $S$ - исправленное СКО (из 2ой ПР)



Поскольку функция $S(t, N)$ является четной, справедливо соотношение:
$$P(|\frac{\overline{x}_в - a}{S/\sqrt{N}}|<t_γ) = 2 ∫_0^{t_γ}S(t, N)dt = γ$$

$$ => P(\overline{x}_в - t_γ*S/\sqrt{N} < a < \overline{x}_в + t_γ*S/\sqrt{N}) = γ$$

*__В результате требуемый доверительный интервал__*, покрывающий неизвестное значение параметра $a$ с надежностью $γ$ принимает следующий вид:
$$(\overline{x}_в - \frac{t_γ*S}{\sqrt{N}} ; \overline{x}_в + \frac{t_γ*S}{\sqrt{N}})$$

где точность $δ$ = $t_γ*S/\sqrt{N}$.

($t_γ$ можно определить с использованием таблицы из Приложения 6)

In [35]:
# Подключение библиотек
import math
import pandas # Для представления в табличной форме

Определим $t_γ$ согласно таблице из Приложения 6 (из материалов se.moevm.info) для заданных $γ∈\{0.95,0.99\}$ и $N=117$:

- $t_γ∈\{1.98, 2.617\}$

In [7]:
t_gamma = [1.98, 2.617]

Определим точность:

$δ = t_γ*S/\sqrt{N}$

In [8]:
# Использование результатов 2 ПР
# Исправленное СКО
S = 55.776
# Выборочное среднее
sample_mean = 454.58

# Объем выборки
N = 117

# Функция вычисления точности δ по формуле
def get_sigma(S, t_gamma, N):
  return [t_gamma[0] * S / math.sqrt(N), t_gamma[1] * S / math.sqrt(N)]
sigma = get_sigma(S, t_gamma, N)
print('Точность δ при γ=0.95: {},\nТочность δ при γ=0.99: {} '.format(sigma[0], sigma[1]))

Точность δ при γ=0.95: 10.209856187737264,
Точность δ при γ=0.99: 13.494542244095165 


Вычислим доверительный интервал (ДИ), который имеет вид:
$$(\overline{x}_в - \frac{t_γ*S}{\sqrt{N}} ; \overline{x}_в + \frac{t_γ*S}{\sqrt{N}})$$


$$Т.е. \ (\overline{x}_в - δ; \ \overline{x}_в + δ)$$

In [9]:
# Функция вычисления ДИ
def get_DI(sample_mean, sigma):
  return [sample_mean - sigma, sample_mean + sigma]

# Вычисление ДИ при γ=0.95
first_di = get_DI(sample_mean, sigma[0])
print('При γ=0.95 ДИ: ({}; {})'.format(first_di[0], first_di[1]))
print('При γ=0.95 Точность δ: {}\n'.format(sigma[0]))

# Вычисление ДИ при γ=0.99
second_di = get_DI(sample_mean, sigma[1])
print('При γ=0.99 ДИ: ({}; {})'.format(second_di[0], second_di[1]))
print('При γ=0.99 Точность δ: {}'.format(sigma[1]))

При γ=0.95 ДИ: (444.3701438122627; 464.78985618773726)
При γ=0.95 Точность δ: 10.209856187737264

При γ=0.99 ДИ: (441.0854577559048; 468.07454224409514)
При γ=0.99 Точность δ: 13.494542244095165


*__Промежуточные выводы:__*

&emsp;Вычислив *доверительные интервалы*, которые с заданными доверительными вероятностями покрывают истинное значение математического ожидания, можем заключить, что: <br>
* Истинное значение МО с надежностью $γ=0.95$ содержится в ДИ $$(444.37014; 464.78986)$$
* Истинное значение МО с надежностью $γ=0.99$ содержится в ДИ $$(441.08546; 468.07454)$$
* Значение выборочного среднего ($\overline{x}_в =454.58$) - статистическая оценка параметра математического ожидания выборки - принадлежит полученным доверительным интервалам.

&emsp;Также по результатам программных вычислений можем подтвердить, что при большем значении точности $δ$ доверительный интервал "шире", а значит оценка параметра менее точная, хоть и с большей доверительной вероятностью. Точность оценки параметра можно увеличить (т.е. уменьшить значение $δ$ = $t_γs/\sqrt{N}$, не уменьшая доверительную вероятность), можно, увеличив объем выборки $N$.

### *__Задание 2__*
*Для вычисления границ доверительного интервала для среднеквадратичного отклонения определить значение $q$ при заданных $γ$ и $n$. Построить доверительные интервалы, сделать выводы.*

*__Доверительный интервал для среднеквадратического отклонения (СКВО)__*<br><br>
*__Воспользуемся выкладками из лекционной презентации.__*

&emsp; Требуется построить ДИ, покрывающий с надежностью $γ$ неизвестное значение параметра $σ$ - СКВО случайной величины $X$.

&emsp;Запишем соотношение $P(|S-σ|<δ)=γ$ и равносильное ему:
$$P(S-δ<σ<S+δ)=γ$$
&emsp;Проведем преобразование двойного неравенства $$S-δ<σ<S+δ$$ к виду:
$$S(1-δ/S)<σ<S(1+δS)$$
&emsp;Вводится обозначение: $q = δ/S$, тогда:
$$S(1-q)<σ<S(1+q)$$
&emsp;Предполагая $q<1$ перепишем в виде:
$$\frac{1}{S(1+q)}<\frac{1}{σ}<\frac{1}{S(1-q)}$$
&emsp;Умножим неравенство на $S\sqrt{N-1}$:
$$\frac{\sqrt{N-1}}{(1+q)}<\frac{S\sqrt{N-1}}{σ}<\frac{\sqrt{N-1}}{(1-q)}$$
&emsp;Введем в расммотрение случайную величину $χ$:
$$χ = \frac{S\sqrt{N-1}}{σ}$$

&emsp;Функция плотности вероятности $R(χ, N)$ распределения случайной величины $χ$ зависит только от $N$.

&emsp;Тогда перепишем в виде:
$$\frac{\sqrt{N-1}}{(1+q)}<χ<\frac{\sqrt{N-1}}{(1-q)}$$

&emsp;Потребуем, чтобы вероятность выполнения двойного неравенства равнялась, $γ$:
$$∫_{\sqrt{N-1}/(1+q)}^{\sqrt{N-1}/(1-q)}R(χ, N)dχ = γ$$

&emsp;Значение $q$, при котором, при заданных значениях $γ$ и $N$, оно выполняется, определяется по соответствующей таблице из *__Приложения 7__*.

&emsp;В результате получили *__требуемый доверительный интервал__*, покрывающий неизвестное значение параметра $σ$ с надежностью $γ$:
$$(S(1-q), S(1+q))$$

Определим $q$ согласно таблице из Приложения 7 (из материалов se.moevm.info) для заданных $γ∈\{0.95,0.99\}$ и $N=117$:

- $q∈\{0.143, 0.198\}$

In [10]:
q = [0.143, 0.198]

Тогда, используя значения $q$ и исправленное СКО - $S$ (из ПР 2, переменная $S$ инициализирована в предыдущем пункте), вычислим ДИ:
$$(S(1-q), S(1+q))$$

In [11]:
# Функция вычисления ДИ при известном СКО
def get_DI_known_SKO(S, q):
  return [ S*(1-q),  S*(1+q)]

# Вычисление ДИ при γ=0.95
di_1_known_SKO = get_DI_known_SKO(S, q[0])
print('При γ=0.95 ДИ: ({}; {})'.format(di_1_known_SKO[0], di_1_known_SKO[1]))
print('При γ=0.95 Значение q из Приложения 7: {}\n'.format(q[0]))

# Вычисление ДИ при γ=0.99
di_2_known_SKO = get_DI_known_SKO(S, q[1])
print('При γ=0.99 ДИ: ({}; {})'.format(di_2_known_SKO[0], di_2_known_SKO[1]))
print('При γ=0.99 Значение q из Приложения 7: {}'.format(q[1]))

При γ=0.95 ДИ: (47.800032; 63.751968000000005)
При γ=0.95 Значение q из Приложения 7: 0.143

При γ=0.99 ДИ: (44.732352000000006; 66.819648)
При γ=0.99 Значение q из Приложения 7: 0.198


**Промежуточные выводы:**

&emsp;Используя исправленное СКО ($S=55.776$) из Практической Работы №2, были вычислены доверительные интервалы при заданных доверительных вероятностях для истинного значения среднеквадратичного отклонения:
* Истинное значение СКО с надежностью $γ=0.95$ содержится в ДИ $$(47.80003; 63.75197)$$
* Истинное значение СКО с надежностью $γ=0.99$ содержится в ДИ $$(44.732352000000006; 66.819648)$$
* Значение исправленного СКО ($S=55.776$) - статистическая оценка параметра $σ$ СКО - принадлежит полученным доверительным интервалам.

&emsp;Также по результатам программных вычислений можем подтвердить, что при большей точности $δ$, т.е. при большем значении $q$ (поскольку прямопропорциональная зависимость $δ = qS$) доверительный интервал "шире", а значит оценка параметра менее точная, хоть и с большей доверительной вероятностью.

### *__Задание 3__*
*Проверить гипотезу о нормальности заданного распределения с помощью критерия $\chi^2$ (Пирсона). Для этого необходимо найти теоретические частоты и вычислить наблюдаемое значение критерия. Для удобства вычисления необходимо заполнить табл. 1.*

&emsp;Пусть нулевая гипотеза $H_0$ (т.е. выдвинутая) - гипотеза о нормальности распределения выборки (значения выборки - значения случайной величины).

&emsp;Проверим данную гипотезу.<br>
&emsp;В качестве критерия проверки гипотезы будет использован критерий Пирсона (правосторонний критерий):
$$χ^2_{набл} = \sum^K_{i=1} \frac{(n_i - n_i')^2}{n_i'} $$

&emsp;где $n_i'$ - *__теоретические частоты__*<br>
&emsp;(т.е. частоты, с которыми нормально распределенная величина с параметрами $\overline{x_в}$ и $S$ попала бы в $i$-й интервал интервального ряда при проведении $N$ испытаний)




&emsp;Для вычисления значения $χ^2_{набл}$ необходимо вычислить значения $n_i'$ - теоретических частот <br>
(*__для этого воспользуемся выкладками из лекционной презентации__*):

1.  &emsp; Пересчитать значения границ интервалов интервального ряда. При этом левую границу первого интервала назначить равной $-∞$ ($z_1 = -∞)$, а правую границу последнего интервала назначить равной $+∞$ ($z_{K+1} = +∞)$. Остальные значения вычислить по формуле: $$z_i = \frac{x_i - \overline{x_в}}{S}, i = 2, 3, ..., K$$






In [80]:
# В соответствии с интервальным рядом, кол-во интервалов
K = 7

# Новые границы интервалов
z = []

# Исходные значения границ из интервального ряда
base_borders = [351, 386, 421, 456, 491, 526, 561, 596]
# Заменяем первую и последнюю границу
borders = [-math.inf, 386, 421, 456, 491, 526, 561, math.inf]

# Самая левая, первая граница
z.append(borders[0])

# Пересчёт значений границ z_i согласно формуле, с округлением до 2х знаков
for i in range(1, K):
  z.append(round((borders[i] - sample_mean)/S, 2))

# Самая правая, последняя граница
z.append(borders[-1])

print('Количество интервалов: {}'.format(K))
print('Границы интервалов z_i:', z)

Количество интервалов: 7
Границы интервалов z_i: [-inf, -1.23, -0.6, 0.03, 0.65, 1.28, 1.91, inf]


2.   &emsp;Вычислить вероятность попадания случайной величины в каждый $i$-й интервал интервального ряда: $$p_i = Ф(z_{i+1}) - Ф(z_{i}), \ i = 1, 2, 3, ..., K$$
где $Ф(z)$ - функция Лапласа: $$Ф(z) = \frac{1}{\sqrt{2π}}∫_0^ze^{-\frac{t^2}{2}}dt$$
&emsp;Значения этой функции можно взять из Приложения 4. Нужно учитывать нечетность этой функции и то, что: $$Ф(-∞) = -0.5$$ $$Ф(+∞) = 0.5$$

In [81]:
# Значения функции Лапласа из Приложения 4
laplas_values = [-0.5, -0.3883, -0.2257, 0.0120, 0.2422, 0.3883, 0.4719, 0.5]
print('Значения функции Лапласа Ф(z_i) из Приложения 4:\n', laplas_values)

Значения функции Лапласа Ф(z_i) из Приложения 4:
 [-0.5, -0.3883, -0.2257, 0.012, 0.2422, 0.3883, 0.4719, 0.5]


3. &emsp;Вычислить значения теоретических частот: $$n_i' = N \cdot p_i, \ i = 1, 2, 3, ..., K$$
&emsp;где $p_i$ - вероятность попадания значения случайной величины в i-ый интервал интервального ряда.

&emsp;Сначала вычислим вероятности попадания значения случайной величины в i-ый интервал интервального ряда, а затем и теоретические частот согласно формуле, приведенной выше:

In [82]:
# Вычисление p_i
# Вероятность попадания значения случайной величины
# в i-й интервал интервального ряда
p = []
for i in range(0, K):
  p.append(round(laplas_values[i+1] - laplas_values[i], 4)) # Округление до 4 знаков

# Вычисление n'_i - теоретических частот
teor_n_i = [N * p_i for p_i in p]

# Вывод результата
print('p_i - Вероятности попадания в i-ый интервал интерв. ряда:')
print(p, '\n')
print('n`_i - Теоретические частоты:')
print(teor_n_i)

p_i - Вероятности попадания в i-ый интервал интерв. ряда:
[0.1117, 0.1626, 0.2377, 0.2302, 0.1461, 0.0836, 0.0281] 

n`_i - Теоретические частоты:
[13.0689, 19.0242, 27.8109, 26.9334, 17.093700000000002, 9.7812, 3.2877]


&emsp;Введем абсолютные частоты для интервалов, полученные в ПР №1:

In [83]:
# Абсолютные частоты для интервалов, полученные в ПР №1:
n_i = [11, 18, 33, 27, 18, 5, 5]

&emsp;Представим вычисления в табличной форме:

In [84]:
# Границы интервалов, x_i, x_i+1
left_borders = base_borders[0:K]
right_borders = base_borders[K:0:-1][::-1] # С реверсом
# Соединение в интервалы
intervals= []
for i in range(len(left_borders)):
  intervals.append((left_borders[i], right_borders[i]))

# Вычисление колонок с частотами (квадраты разности, дроби и т.д.)
six_col = [(n_i[i] - teor_n_i[i])**2 for i in range(K)]
seven_col = [round(six_col[i] / teor_n_i[i], 4) for i in range(K)]
eight_col = [elem**2 for elem in n_i]
nine_col = [round(eight_col[i] / teor_n_i[i], 4) for i in range(K)]

# Создание строки суммирующих элементов
indexes = list(range(1, K+1))
indexes.append('Σ')
intervals.append('-')
n_i_col = n_i
n_i_col.append(sum(n_i))
p_i_col = p
p_i_col.append(sum(p))
teor_n_i_col = teor_n_i
teor_n_i_col.append(sum(teor_n_i))
six_col.append('-')
seven_col.append(sum(seven_col))
eight_col.append('-')
nine_col.append(sum(nine_col))

# Создание необходимых колонок Таблицы 1
table_df = pandas.DataFrame({'i': indexes})
table_df["[x_i, x_i+1)"] = intervals
table_df["n_i"] = n_i_col
table_df["p_i"] = p_i_col
table_df["n`_i"] = teor_n_i_col
table_df["(n_i-n`i)^2"] = six_col
table_df["(n_i-n'i)^2 / n'_i"] = seven_col
table_df["(n_i)^2"] = eight_col
table_df["(n_i)^2 / n'_i"] = nine_col


# Отображение Таблицы 1
df_styler = table_df.style.set_properties(**{'text-align': 'center'})
df_styler.hide(axis='index')

&emsp;В качестве критерия проверки гипотезы будет использован критерий Пирсона:
$$χ^2_{набл} = \sum^K_{i=1} \frac{(n_i - n_i')^2}{n_i'} $$

&emsp;Вычислим значения $χ^2_{набл}$ согласно формуле, используя найденные значения теоретических частот.

In [86]:
# Вычисление набл. χ^2 согласно формуле
x_square = 0

for i in range(K):
  x_square += ((n_i[i] - teor_n_i[i]) ** 2) / teor_n_i[i]

print('Значение χ^2 набл.: {}'.format(round(x_square, 3)))

Значение χ^2 набл.: 4.628


Получили, что $χ^2_{набл} = 4.628$

&emsp;Распределение $χ^2$ зависит от числа свободы $k$, которое вычисляется по формуле (для нормального распределения):
$$k = K - 3 = 7-3=4$$где K - количество интервалов.
<br>
&emsp;По числу степеней свободы и уровню значимости вычисляется значение $χ^2_{крит} = χ^2(α,k)$. Это значение можно определить с помощью таблицы из Приложения 5.

&emsp;Пусть уровень значимости $\alpha = 0.05$. Число степеней свободы, как посчитали выше, $k=4$. Тогда согласно таблице из Приложения 5:
$$χ^2_{крит} = χ^2(α,k)=χ^2(0.05,4)=9.5$$

&emsp;Получается, что $$χ^2_{набл} ≈ 4.628$$ $$χ^2_{крит} = 9.5$$ $$χ^2_{набл} < χ^2_{крит}$$

&emsp;Поскольку критерий Пирсона *правосторонний*, т.е. критическая область (*__область непринятия гипотезы__*) определяется неравенством $$K_{набл} > K_{крит}$$то поскольку $χ^2_{набл} < χ^2_{крит}$ - *__нулевая гипотеза $H_0$ принимается__*.

&emsp;Но следует отметить, что принятие гипотезы не означает ее справедливость, а лишь констатирует, что в соответствии с используемым критерием и уровнем значимости, гипотеза согласуется с данными наблюдений.

### *__Задание 4__*
*Доказать, что $$\chi^2_{\textit{набл}} = \sum_{i = 1}^k\frac{n^2_i}{n'_i} - N.$$ Проконтролировать корректность вычисления $\chi^2_{\textit{набл}}$\**

*__Доказательство:__*

&emsp;Критерий Пирсона: $$χ^2_{набл} = \sum^K_{i=1} \frac{(n_i - n_i')^2}{n_i'} $$

&emsp; Преобразуем:

$$χ^2_{набл} = \sum^K_{i=1} \frac{(n_i - n_i')^2}{n_i'}  = \sum^K_{i=1} \frac{n_i^2 - 2 n_i n_i' + n_i'^2}{n_i'} = \sum^K_{i=1}\frac{n_i^2}{n_i'} - \sum^K_{i=1} \frac{ 2 n_i n_i'}{n_i'} + \sum^K_{i=1} \frac{ n_i'^2}{n_i'} = \sum^K_{i=1}\frac{n_i^2}{n_i'} - 2\sum^K_{i=1} n_i + \sum^K_{i=1} n_i'$$

&emsp;Поскольку можем утверждать, что $\sum^K_{i=1} n_i = \sum^K_{i=1} n_i' = N$ (*в Таблице 1 это подтверждается*), то далее можно преобразовать: $$\chi^2_{\textit{набл}} = \sum^K_{i=1}\frac{n_i^2}{n_i'} - 2\sum^K_{i=1} n_i + \sum^K_{i=1} n_i' =\sum_{i = 1}^k\frac{n^2_i}{n'_i} - 2N + N = \sum_{i = 1}^k\frac{n^2_i}{n'_i} - N$$
&emsp;что и требовалось доказать.

*__Контроль корректности вычисления__* $\chi^2_{\textit{набл}}*$:

&emsp;Проверим $$\chi^2_{\textit{набл}}*=\sum_{i = 1}^k\frac{n^2_i}{n'_i} - N$$

&emsp;Согласно Таблице 1: $$\sum_{i = 1}^k\frac{n^2_i}{n'_i} = 121.628$$
&emsp;Объем выборки $N=117$

&emsp;Тогда, $$\chi^2_{\textit{набл}}*=\sum_{i = 1}^k\frac{n^2_i}{n'_i} - N = 121.628 - 117=4.628$$

&emsp;А программно-вычисленный $\chi^2_{\textit{набл}}=4.628$

&emsp;Таким образом,
$$\chi^2_{\textit{набл}}*=\chi^2_{\textit{набл}}=4.628$$
&emsp;Значения совпали, значит, вычисления выполнены верно.


### *__Задание 5__*

*По заданному уровню значимости $\alpha = 0.05$ и числу степеней свободы $df$ найти критическую точку $\chi^2_{\textit{крит}}$ и сравнить с наблюдаемым значением.*

&emsp;По числу степеней свободы и уровню значимости вычисляется значение критической точки: $$χ^2_{крит} = χ^2(α,k)$$ &emsp;Это значение было определено в Задании 4 (при $\alpha = 0.05$) с помощью таблицы из Приложения 5.

&emsp;При $\alpha = 0.05$ и числу степеней свободы (как посчитали выше) $k=4$ значение критической точки:
$$χ^2_{крит} = χ^2(α,k)=χ^2(0.05,4)=9.5$$

 &emsp;Значение $\chi^2_{\textit{набл}}$ оказалось меньше $\chi^2_{\textit{крит}}$, что соответствует области принятия гипотезы, поэтому нулевая гипотеза была принята.

*__Промежуточные выводы:__*

&emsp;В результате проверки нулевой гипотезы о нормальности заданного распределения с помощью критерия Пирсона нулевая гипотеза была принята. Но это не означает справедливость того, что заданное распределение является нормальным, а лишь *__констатирует__*, что *__в соответствии с используемым критерием и уровнем значимости $\alpha = 0.05$, гипотеза согласуется с данными наблюдений__*.

## Выводы

&emsp;В результате выполнения работы были изучены интервальные статистические оценки параметров распределения выборочных данных, алгоритмы нахождения доверительных интервалов при известном и неизвестном СКО, а также принципы проверки статистических гипотез.

&emsp;В ходе работы были найдены ДИ с заданными доверительными вероятностями, а также сделан вывод о том, что точность оценки параметра можно увеличить (т.е. уменьшить значение $δ$, не уменьшая доверительную вероятность), можно, увеличив объем выборки $N$.

&emsp;Для проверки статистической гипотезы о нормальности распределения заданного распределения был использован критерий Пирсона. Рассчитав $χ^2_{набл}$ и сравнив его с найденным $χ^2_{крит}$, в соответствии с критерием и уровнем значимости $α=0.05$, нулевая гипотеза была принята. Однако это не означает ее справедливость, а лишь констатирует, что в соответствии с используемым критерием и уровнем значимости, гипотеза согласуется с данными наблюдений.

&emsp;Вычисление значения $χ^2_{набл}$ было проконтролировано с помощью доказанного равенства.


